version: "3.8"

services:
  leviathan:
    build: .
    container_name: leviathan
    restart: always
    ports:
      - "22:2222"
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./store:/app/store
    environment:
      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
      API_SECRET_KEY: ${API_SECRET_KEY}
    env_file:
      - .env
    command: ["python", "-u", "leviathan.py", "-a", "0.0.0.0", "-p", "2222", "-c", "${CONFIG_PATH:-/app/configs/config.yaml}"]

