version: "3.8"

services:
  leviathan:
    build: .
    container_name: leviathan
    restart: always
    ports:
      - "22:2222"
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./store:/app/store
    environment:
      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
      API_SECRET_KEY: ${API_SECRET_KEY}
      ELK_ENABLED: "true"
      ES_HOST: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    command: ["python", "-u", "leviathan.py", "-a", "0.0.0.0", "-p", "2222", "-c", "${CONFIG_PATH:-/app/configs/config.yaml}"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  nginx:
    image: nginx:alpine
    container_name: kibana-proxy
    depends_on:
      - kibana
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro

volumes:
  esdata:

