#llmProvider: "deepseek"
llmProvider: "openai"
#llmProvider: "grok"
llmModel: "gpt-4o-mini"
#llmModel: "deepseek-chat"
#llmModel: "ft:gpt-4o-2024-08-06:my-org:unix-shell:BBLTnk8Q"
#llmModel: "grok-3-mini-fast-beta"
#apiSecretKey: "sk-6f9c885dd73440329fd0500c560fc7c9"
apiSecretKey: "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"
#apiSecretKey: "xai-qvjixi6epIgc94E5Rf414EGbhkvk8zTn0XZb5SvI8MMW36nuDTG272wDinKbwXAFYVf4mqVQfHVQaOAH"